# Configuration for autolabeler - https://github.com/probot/autolabeler

components: ['/src']
documentation: ['*.md']
example: ['/examples']
tooling: [
  '.babelrc',
  'jest.config.js',
  '*.json',
  '*.yml',
  '.github',
  '.ci',
  '.storybook',
]
