# Configuration for autolabeler - https://github.com/probot/autolabeler

components: ['/src']
documentation: ['/docs']
example: ['/examples']
tooling:
  [
    './*.js',
    './.*.js',
    './*.json',
    './.*.json',
    './*.yml',
    './.*.yml',
    '.github',
    '.ci',
    '.storybook',
  ]
